{
    "name": "Cartoon Storage",
    "version": "1.0",
    "summary": "Module to manage files and images with storage connection via fsspec.",
    "author": "Generated by Assistant",
    "category": "Tools",
    "depends": ["base"],
    "python": ["fsspec"],
    "data": [
        "data/cartoon.resolution.csv",

        "security/ir.model.access.csv",
        "security/ir.rule.xml",

        "views/cartoon_menus.xml",
        "views/cartoon_storage_views.xml",
        "views/cartoon_path_views.xml",
        "views/cartoon_path_extension_views.xml",
        "views/cartoon_image_views.xml",
        "views/cartoon_tag_views.xml",
        "views/cartoon_resolution.xml",


    ],
    "installable": True,
    "application": True,
}